import {MigrationInterface, QueryRunner} from "typeorm";

export class sob21600629983513 implements MigrationInterface {
    name = 'sob21600629983513'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("CREATE TABLE `branch` (`idBran` varchar(36) NOT NULL, `name` varchar(100) NOT NULL, `address` varchar(40) NOT NULL, `city` varchar(40) NOT NULL, `telephone` varchar(15) NOT NULL, `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `companyIdCom` varchar(36) NULL, PRIMARY KEY (`idBran`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `company` (`idCom` varchar(36) NOT NULL, `name` varchar(50) NOT NULL, `nit` varchar(30) NOT NULL, `country` varchar(50) NOT NULL, `address` varchar(40) NOT NULL, `city` varchar(40) NOT NULL, `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX `IDX_7917f87e3719deca503c1e847e` (`nit`), PRIMARY KEY (`idCom`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `roles` (`idRole` int NOT NULL AUTO_INCREMENT, `name` varchar(20) NOT NULL, `description` text NOT NULL, `status` varchar(8) NOT NULL DEFAULT 'ACTIVE', `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`idRole`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `customer` (`idCustomer` varchar(255) NOT NULL, `customer_type` varchar(20) NOT NULL, `email` varchar(100) NULL, `phone` varchar(20) NULL, `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX `REL_2a432ec72f3dd1b35324825948` (`idCustomer`), PRIMARY KEY (`idCustomer`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `PaymentMethod` (`idPayment_method` varchar(36) NOT NULL, `name` varchar(255) NOT NULL, `description` varchar(255) NOT NULL, `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`idPayment_method`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `sale_detail` (`idSale` varchar(36) NOT NULL, `quantity` int NOT NULL DEFAULT 1, `sub_total` double NOT NULL, `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `saleIdSale` varchar(36) NULL, `ticketIdTicket` varchar(36) NULL, `ticketIdPassenger` varchar(255) NULL, `ticketIdTrip` varchar(255) NULL, PRIMARY KEY (`idSale`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `sale` (`idSale` varchar(36) NOT NULL, `total_sale` double NOT NULL, `type_sale` varchar(10) NOT NULL, `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `customerIdCustomer` varchar(36) NULL, `paymentMethodIdPaymentMethod` varchar(36) NULL, PRIMARY KEY (`idSale`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `sale_cash` (`idCash_sale` varchar(255) NOT NULL, `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `userIdUser` varchar(36) NULL, UNIQUE INDEX `REL_66d7aab188bbfc17b3eb409689` (`idCash_sale`), PRIMARY KEY (`idCash_sale`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `UserStaff` (`idUser` varchar(36) NOT NULL, `username` varchar(20) NOT NULL, `password` varchar(255) NOT NULL, `status` varchar(8) NOT NULL DEFAULT 'ACTIVE', `salt` varchar(255) NOT NULL, `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `staffIdStaff` varchar(255) NULL, `roleIdRole` int NULL, UNIQUE INDEX `IDX_dad68a1d231866a4f0b2caa13d` (`username`), UNIQUE INDEX `REL_7e5135119571406777298b844c` (`staffIdStaff`), PRIMARY KEY (`idUser`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `Staff` (`idStaff` varchar(255) NOT NULL, `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `companyIdCom` varchar(36) NULL, UNIQUE INDEX `REL_2bdc5ca92422a75e4556740ae6` (`idStaff`), PRIMARY KEY (`idStaff`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `Person` (`idPerson` varchar(36) NOT NULL, `name` varchar(200) NOT NULL, `lastname` varchar(100) NULL, `type_doc` varchar(10) NOT NULL, `document` varchar(25) NOT NULL, `phone` varchar(15) NULL, `nationality` varchar(25) NULL, `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX `IDX_b4ec17d7e0135a1ecaf15b4ffc` (`document`), PRIMARY KEY (`idPerson`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `Bus_normal` (`idBus_normal` varchar(255) NOT NULL, `nro_seats` int NOT NULL, `nro_rows` int NOT NULL, `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX `REL_9ad9d8d601d459113e26354aa0` (`idBus_normal`), PRIMARY KEY (`idBus_normal`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `Bus_dp` (`idBusdp` varchar(255) NOT NULL, `NA_P1` int NOT NULL, `NA_P2` int NOT NULL, `NF_P1` int NOT NULL, `NF_P2` int NOT NULL, `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX `REL_3e3dd36ed5d041e6cfe9f595d3` (`idBusdp`), PRIMARY KEY (`idBusdp`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `Driver` (`idDriver` varchar(255) NOT NULL, `nro_licence` varchar(255) NOT NULL, `category` varchar(255) NOT NULL, `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX `REL_964470075b3a332aafe6d10acd` (`idDriver`), PRIMARY KEY (`idDriver`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `Bus` (`idBus` varchar(36) NOT NULL, `type_bus` varchar(20) NOT NULL, `plate_number` varchar(20) NOT NULL, `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `driverIdDriver` varchar(36) NULL, UNIQUE INDEX `IDX_ee1122521551ea703e805938fa` (`plate_number`), UNIQUE INDEX `REL_b35f1be2cdcb66bf90568da381` (`driverIdDriver`), PRIMARY KEY (`idBus`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `route` (`idRoute` varchar(36) NOT NULL, `city` varchar(20) NOT NULL, `terminal` varchar(255) NOT NULL, `address` varchar(255) NOT NULL, `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`idRoute`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `trip` (`idTrip` varchar(36) NOT NULL, `duration` time NOT NULL, `departure_date` date NOT NULL, `departure_time` time NOT NULL, `arrival_date` date NULL, `arrival_time` time NOT NULL, `status` varchar(255) NOT NULL DEFAULT 'ON_HOLD', `min_price` double NOT NULL, `max_price` double NOT NULL, `price_online` double NOT NULL, `codigo_trip` varchar(255) NOT NULL, `carril` varchar(255) NOT NULL, `mode` varchar(255) NOT NULL, `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `originIdRoute` varchar(36) NULL, `destinationIdRoute` varchar(36) NULL, `busIdBus` varchar(36) NULL, PRIMARY KEY (`idTrip`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `Ticket` (`idTicket` varchar(36) NOT NULL, `idPassenger` varchar(255) NOT NULL, `idTrip` varchar(255) NOT NULL, `nro_seat` int NOT NULL, `code` varchar(255) NOT NULL, `sale_price` double NOT NULL, `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`idTicket`, `idPassenger`, `idTrip`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `Booking_detail` (`idBooking_detail` varchar(36) NOT NULL, `subtotal` double NOT NULL, `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `bookingIdBooking` varchar(36) NULL, `ticketIdTicket` varchar(36) NULL, `ticketIdPassenger` varchar(36) NULL, `ticketIdTrip` varchar(36) NULL, PRIMARY KEY (`idBooking_detail`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `Booking` (`idBooking` varchar(36) NOT NULL, `code` varchar(7) NOT NULL, `type_booking` varchar(10) NOT NULL, `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX `IDX_35f9f64406cfac5bf780c1e8ff` (`code`), PRIMARY KEY (`idBooking`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `Booking_cash` (`idBooking_cash` varchar(36) NOT NULL, `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `bookingIdBooking` varchar(36) NOT NULL, `userStaffIdUser` varchar(36) NULL, UNIQUE INDEX `REL_27758a25a297727a79e89c609e` (`bookingIdBooking`), PRIMARY KEY (`idBooking_cash`, `bookingIdBooking`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `sale_online` (`idOnline_sale` varchar(255) NOT NULL, `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `userIdUser` varchar(36) NULL, UNIQUE INDEX `REL_38dbeb5a1d3b339b50c943cf4c` (`idOnline_sale`), PRIMARY KEY (`idOnline_sale`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `UserCustomer` (`idUser` varchar(36) NOT NULL, `name` varchar(100) NULL, `email` varchar(50) NOT NULL, `password` varchar(255) NOT NULL, `status` varchar(8) NOT NULL DEFAULT 'ACTIVE', `status_email` varchar(10) NOT NULL DEFAULT 'VERIFIED', `salt` varchar(255) NOT NULL, `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX `IDX_fffca83b59613d00d9624686c9` (`email`), PRIMARY KEY (`idUser`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `Booking_online` (`idBooking_online` varchar(36) NOT NULL, `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `bookingIdBooking` varchar(36) NOT NULL, `userCustomerIdUser` varchar(36) NULL, UNIQUE INDEX `REL_7eefe0c9ccda410da05397500d` (`bookingIdBooking`), PRIMARY KEY (`idBooking_online`, `bookingIdBooking`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("CREATE TABLE `Tripulation` (`idTripulation` varchar(36) NOT NULL, `helper` varchar(255) NULL, `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `driverIdDriver` varchar(36) NULL, UNIQUE INDEX `REL_673e21295464ed6462213941e5` (`driverIdDriver`), PRIMARY KEY (`idTripulation`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("ALTER TABLE `branch` ADD CONSTRAINT `FK_de7af2b70a995d8c67a078b2991` FOREIGN KEY (`companyIdCom`) REFERENCES `company`(`idCom`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `customer` ADD CONSTRAINT `FK_2a432ec72f3dd1b353248259484` FOREIGN KEY (`idCustomer`) REFERENCES `Person`(`idPerson`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `sale_detail` ADD CONSTRAINT `FK_b4eefda9e14f856e0d9dbbfa413` FOREIGN KEY (`saleIdSale`) REFERENCES `sale`(`idSale`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `sale_detail` ADD CONSTRAINT `FK_15b4fb58d3f201de3ffe99bdd95` FOREIGN KEY (`ticketIdTicket`, `ticketIdPassenger`, `ticketIdTrip`) REFERENCES `Ticket`(`idTicket`,`idPassenger`,`idTrip`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `sale` ADD CONSTRAINT `FK_76ae7e590b17cb741b4fc1218e2` FOREIGN KEY (`customerIdCustomer`) REFERENCES `customer`(`idCustomer`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `sale` ADD CONSTRAINT `FK_81171981eafd73fe57d7944cf99` FOREIGN KEY (`paymentMethodIdPaymentMethod`) REFERENCES `PaymentMethod`(`idPayment_method`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `sale_cash` ADD CONSTRAINT `FK_66d7aab188bbfc17b3eb409689b` FOREIGN KEY (`idCash_sale`) REFERENCES `sale`(`idSale`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `sale_cash` ADD CONSTRAINT `FK_89e45dfc0de4dc6749c124c51cc` FOREIGN KEY (`userIdUser`) REFERENCES `UserStaff`(`idUser`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `UserStaff` ADD CONSTRAINT `FK_7e5135119571406777298b844c9` FOREIGN KEY (`staffIdStaff`) REFERENCES `Staff`(`idStaff`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `UserStaff` ADD CONSTRAINT `FK_0e68a35570443b1c983c5759597` FOREIGN KEY (`roleIdRole`) REFERENCES `roles`(`idRole`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `Staff` ADD CONSTRAINT `FK_2bdc5ca92422a75e4556740ae60` FOREIGN KEY (`idStaff`) REFERENCES `Person`(`idPerson`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `Staff` ADD CONSTRAINT `FK_73841845ee4717d18d3fe5f653f` FOREIGN KEY (`companyIdCom`) REFERENCES `company`(`idCom`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `Bus_normal` ADD CONSTRAINT `FK_9ad9d8d601d459113e26354aa01` FOREIGN KEY (`idBus_normal`) REFERENCES `Bus`(`idBus`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `Bus_dp` ADD CONSTRAINT `FK_3e3dd36ed5d041e6cfe9f595d37` FOREIGN KEY (`idBusdp`) REFERENCES `Bus`(`idBus`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `Driver` ADD CONSTRAINT `FK_964470075b3a332aafe6d10acd4` FOREIGN KEY (`idDriver`) REFERENCES `Staff`(`idStaff`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `Bus` ADD CONSTRAINT `FK_b35f1be2cdcb66bf90568da3812` FOREIGN KEY (`driverIdDriver`) REFERENCES `Driver`(`idDriver`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `trip` ADD CONSTRAINT `FK_21e12f58f404c0999a3d139d6b7` FOREIGN KEY (`originIdRoute`) REFERENCES `route`(`idRoute`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `trip` ADD CONSTRAINT `FK_a893e5e7d37d7a31b0838670525` FOREIGN KEY (`destinationIdRoute`) REFERENCES `route`(`idRoute`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `trip` ADD CONSTRAINT `FK_f7a84429e50cb5711b6c0a9e889` FOREIGN KEY (`busIdBus`) REFERENCES `Bus`(`idBus`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `Ticket` ADD CONSTRAINT `FK_64b80600a55c99ba65616eb8ffe` FOREIGN KEY (`idPassenger`) REFERENCES `Person`(`idPerson`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `Ticket` ADD CONSTRAINT `FK_18f59e6f8fef534b055bef81064` FOREIGN KEY (`idTrip`) REFERENCES `trip`(`idTrip`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `Booking_detail` ADD CONSTRAINT `FK_3e5d44b67ebd09f310bd511fa04` FOREIGN KEY (`bookingIdBooking`) REFERENCES `Booking`(`idBooking`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `Booking_detail` ADD CONSTRAINT `FK_26fb32d9b252ce54767508ba451` FOREIGN KEY (`ticketIdTicket`, `ticketIdPassenger`, `ticketIdTrip`) REFERENCES `Ticket`(`idTicket`,`idPassenger`,`idTrip`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `Booking_cash` ADD CONSTRAINT `FK_27758a25a297727a79e89c609ec` FOREIGN KEY (`bookingIdBooking`) REFERENCES `Booking`(`idBooking`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `Booking_cash` ADD CONSTRAINT `FK_581758c2972b2f52a46a34e9033` FOREIGN KEY (`userStaffIdUser`) REFERENCES `UserStaff`(`idUser`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `sale_online` ADD CONSTRAINT `FK_38dbeb5a1d3b339b50c943cf4cf` FOREIGN KEY (`idOnline_sale`) REFERENCES `sale`(`idSale`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `sale_online` ADD CONSTRAINT `FK_b7668cbb0e2b22b68be55a5c638` FOREIGN KEY (`userIdUser`) REFERENCES `UserCustomer`(`idUser`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `Booking_online` ADD CONSTRAINT `FK_7eefe0c9ccda410da05397500d4` FOREIGN KEY (`bookingIdBooking`) REFERENCES `Booking`(`idBooking`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `Booking_online` ADD CONSTRAINT `FK_edcd4087bcbab8d0b4be94e628c` FOREIGN KEY (`userCustomerIdUser`) REFERENCES `UserCustomer`(`idUser`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `Tripulation` ADD CONSTRAINT `FK_673e21295464ed6462213941e52` FOREIGN KEY (`driverIdDriver`) REFERENCES `Driver`(`idDriver`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("CREATE TABLE `sob2`.`query-result-cache` (`id` int NOT NULL AUTO_INCREMENT, `identifier` varchar(255) NULL, `time` bigint NOT NULL, `duration` int NOT NULL, `query` text NOT NULL, `result` text NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("DROP TABLE `sob2`.`query-result-cache`", undefined);
        await queryRunner.query("ALTER TABLE `Tripulation` DROP FOREIGN KEY `FK_673e21295464ed6462213941e52`", undefined);
        await queryRunner.query("ALTER TABLE `Booking_online` DROP FOREIGN KEY `FK_edcd4087bcbab8d0b4be94e628c`", undefined);
        await queryRunner.query("ALTER TABLE `Booking_online` DROP FOREIGN KEY `FK_7eefe0c9ccda410da05397500d4`", undefined);
        await queryRunner.query("ALTER TABLE `sale_online` DROP FOREIGN KEY `FK_b7668cbb0e2b22b68be55a5c638`", undefined);
        await queryRunner.query("ALTER TABLE `sale_online` DROP FOREIGN KEY `FK_38dbeb5a1d3b339b50c943cf4cf`", undefined);
        await queryRunner.query("ALTER TABLE `Booking_cash` DROP FOREIGN KEY `FK_581758c2972b2f52a46a34e9033`", undefined);
        await queryRunner.query("ALTER TABLE `Booking_cash` DROP FOREIGN KEY `FK_27758a25a297727a79e89c609ec`", undefined);
        await queryRunner.query("ALTER TABLE `Booking_detail` DROP FOREIGN KEY `FK_26fb32d9b252ce54767508ba451`", undefined);
        await queryRunner.query("ALTER TABLE `Booking_detail` DROP FOREIGN KEY `FK_3e5d44b67ebd09f310bd511fa04`", undefined);
        await queryRunner.query("ALTER TABLE `Ticket` DROP FOREIGN KEY `FK_18f59e6f8fef534b055bef81064`", undefined);
        await queryRunner.query("ALTER TABLE `Ticket` DROP FOREIGN KEY `FK_64b80600a55c99ba65616eb8ffe`", undefined);
        await queryRunner.query("ALTER TABLE `trip` DROP FOREIGN KEY `FK_f7a84429e50cb5711b6c0a9e889`", undefined);
        await queryRunner.query("ALTER TABLE `trip` DROP FOREIGN KEY `FK_a893e5e7d37d7a31b0838670525`", undefined);
        await queryRunner.query("ALTER TABLE `trip` DROP FOREIGN KEY `FK_21e12f58f404c0999a3d139d6b7`", undefined);
        await queryRunner.query("ALTER TABLE `Bus` DROP FOREIGN KEY `FK_b35f1be2cdcb66bf90568da3812`", undefined);
        await queryRunner.query("ALTER TABLE `Driver` DROP FOREIGN KEY `FK_964470075b3a332aafe6d10acd4`", undefined);
        await queryRunner.query("ALTER TABLE `Bus_dp` DROP FOREIGN KEY `FK_3e3dd36ed5d041e6cfe9f595d37`", undefined);
        await queryRunner.query("ALTER TABLE `Bus_normal` DROP FOREIGN KEY `FK_9ad9d8d601d459113e26354aa01`", undefined);
        await queryRunner.query("ALTER TABLE `Staff` DROP FOREIGN KEY `FK_73841845ee4717d18d3fe5f653f`", undefined);
        await queryRunner.query("ALTER TABLE `Staff` DROP FOREIGN KEY `FK_2bdc5ca92422a75e4556740ae60`", undefined);
        await queryRunner.query("ALTER TABLE `UserStaff` DROP FOREIGN KEY `FK_0e68a35570443b1c983c5759597`", undefined);
        await queryRunner.query("ALTER TABLE `UserStaff` DROP FOREIGN KEY `FK_7e5135119571406777298b844c9`", undefined);
        await queryRunner.query("ALTER TABLE `sale_cash` DROP FOREIGN KEY `FK_89e45dfc0de4dc6749c124c51cc`", undefined);
        await queryRunner.query("ALTER TABLE `sale_cash` DROP FOREIGN KEY `FK_66d7aab188bbfc17b3eb409689b`", undefined);
        await queryRunner.query("ALTER TABLE `sale` DROP FOREIGN KEY `FK_81171981eafd73fe57d7944cf99`", undefined);
        await queryRunner.query("ALTER TABLE `sale` DROP FOREIGN KEY `FK_76ae7e590b17cb741b4fc1218e2`", undefined);
        await queryRunner.query("ALTER TABLE `sale_detail` DROP FOREIGN KEY `FK_15b4fb58d3f201de3ffe99bdd95`", undefined);
        await queryRunner.query("ALTER TABLE `sale_detail` DROP FOREIGN KEY `FK_b4eefda9e14f856e0d9dbbfa413`", undefined);
        await queryRunner.query("ALTER TABLE `customer` DROP FOREIGN KEY `FK_2a432ec72f3dd1b353248259484`", undefined);
        await queryRunner.query("ALTER TABLE `branch` DROP FOREIGN KEY `FK_de7af2b70a995d8c67a078b2991`", undefined);
        await queryRunner.query("DROP INDEX `REL_673e21295464ed6462213941e5` ON `Tripulation`", undefined);
        await queryRunner.query("DROP TABLE `Tripulation`", undefined);
        await queryRunner.query("DROP INDEX `REL_7eefe0c9ccda410da05397500d` ON `Booking_online`", undefined);
        await queryRunner.query("DROP TABLE `Booking_online`", undefined);
        await queryRunner.query("DROP INDEX `IDX_fffca83b59613d00d9624686c9` ON `UserCustomer`", undefined);
        await queryRunner.query("DROP TABLE `UserCustomer`", undefined);
        await queryRunner.query("DROP INDEX `REL_38dbeb5a1d3b339b50c943cf4c` ON `sale_online`", undefined);
        await queryRunner.query("DROP TABLE `sale_online`", undefined);
        await queryRunner.query("DROP INDEX `REL_27758a25a297727a79e89c609e` ON `Booking_cash`", undefined);
        await queryRunner.query("DROP TABLE `Booking_cash`", undefined);
        await queryRunner.query("DROP INDEX `IDX_35f9f64406cfac5bf780c1e8ff` ON `Booking`", undefined);
        await queryRunner.query("DROP TABLE `Booking`", undefined);
        await queryRunner.query("DROP TABLE `Booking_detail`", undefined);
        await queryRunner.query("DROP TABLE `Ticket`", undefined);
        await queryRunner.query("DROP TABLE `trip`", undefined);
        await queryRunner.query("DROP TABLE `route`", undefined);
        await queryRunner.query("DROP INDEX `REL_b35f1be2cdcb66bf90568da381` ON `Bus`", undefined);
        await queryRunner.query("DROP INDEX `IDX_ee1122521551ea703e805938fa` ON `Bus`", undefined);
        await queryRunner.query("DROP TABLE `Bus`", undefined);
        await queryRunner.query("DROP INDEX `REL_964470075b3a332aafe6d10acd` ON `Driver`", undefined);
        await queryRunner.query("DROP TABLE `Driver`", undefined);
        await queryRunner.query("DROP INDEX `REL_3e3dd36ed5d041e6cfe9f595d3` ON `Bus_dp`", undefined);
        await queryRunner.query("DROP TABLE `Bus_dp`", undefined);
        await queryRunner.query("DROP INDEX `REL_9ad9d8d601d459113e26354aa0` ON `Bus_normal`", undefined);
        await queryRunner.query("DROP TABLE `Bus_normal`", undefined);
        await queryRunner.query("DROP INDEX `IDX_b4ec17d7e0135a1ecaf15b4ffc` ON `Person`", undefined);
        await queryRunner.query("DROP TABLE `Person`", undefined);
        await queryRunner.query("DROP INDEX `REL_2bdc5ca92422a75e4556740ae6` ON `Staff`", undefined);
        await queryRunner.query("DROP TABLE `Staff`", undefined);
        await queryRunner.query("DROP INDEX `REL_7e5135119571406777298b844c` ON `UserStaff`", undefined);
        await queryRunner.query("DROP INDEX `IDX_dad68a1d231866a4f0b2caa13d` ON `UserStaff`", undefined);
        await queryRunner.query("DROP TABLE `UserStaff`", undefined);
        await queryRunner.query("DROP INDEX `REL_66d7aab188bbfc17b3eb409689` ON `sale_cash`", undefined);
        await queryRunner.query("DROP TABLE `sale_cash`", undefined);
        await queryRunner.query("DROP TABLE `sale`", undefined);
        await queryRunner.query("DROP TABLE `sale_detail`", undefined);
        await queryRunner.query("DROP TABLE `PaymentMethod`", undefined);
        await queryRunner.query("DROP INDEX `REL_2a432ec72f3dd1b35324825948` ON `customer`", undefined);
        await queryRunner.query("DROP TABLE `customer`", undefined);
        await queryRunner.query("DROP TABLE `roles`", undefined);
        await queryRunner.query("DROP INDEX `IDX_7917f87e3719deca503c1e847e` ON `company`", undefined);
        await queryRunner.query("DROP TABLE `company`", undefined);
        await queryRunner.query("DROP TABLE `branch`", undefined);
    }

}
