export enum Configuration {
  PORT = 'PORT',
  HOST = 'HOST',
  USERNAME = 'USERNAME',
  PASSWORD = 'PASSWORD',
  DATABASE = 'DATABASE',
  JWT_TOKEN = 'JWT_TOKEN',
  MAILER_SERVICE = 'MAILER_SERVICE',
  USER_MAIL = 'USER_MAIL',
  PASSWORD_MAIL = 'PASSWORD_MAIL',
  DB_PORT = 'DB_PORT',
  CLIENT_SECRET_PAYPAL = 'CLIENT_SECRET_PAYPAL',
  CLIENT_ID_PAYPAL = 'CLIENT_ID_PAYPAL',
}
